default: &default
  adapter: postgresql
  encoding: unicode
  database: onebitexchange
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres


development:
  <<: *default
  database: OneBitExchange_development


test:
  <<: *default
  database: OneBitExchange_test


production:
  <<: *default
  database: OneBitExchange_production
  username: OneBitExchange
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>